export const SEED_HADITHS = [
  { arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ", translation: "Actions are but by intentions.", source: "Sahih al-Bukhari 1" },
  { arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", translation: "The best among you are those who learn the Quran and teach it.", source: "Sahih al-Bukhari 5027" },
  { arabic: "الدِّينُ النَّصِيحَةُ", translation: "Religion is sincerity.", source: "Sahih Muslim 55" },
  { arabic: "مَنْ لَا يَرْحَمُ لَا يُرْحَمُ", translation: "He who does not show mercy will not be shown mercy.", source: "Sahih al-Bukhari 5997" },
  { arabic: "الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ", translation: "A good word is charity.", source: "Sahih al-Bukhari 2989" },
  { arabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبَّ لِنَفْسِهِ", translation: "None of you truly believes until he loves for his brother what he loves for himself.", source: "Sahih al-Bukhari 13" },
  { arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", translation: "Your smile for your brother is charity.", source: "Jami at-Tirmidhi 1956" },
  { arabic: "الطُّهُورُ شَطْرُ الإِيمَانِ", translation: "Purity is half of faith.", source: "Sahih Muslim 223" },
  { arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ", translation: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.", source: "Sahih al-Bukhari 6018" },
  { arabic: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ", translation: "Indeed, Allah is beautiful and He loves beauty.", source: "Sahih Muslim 91" },
  { arabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ", translation: "Whoever takes a path in search of knowledge, Allah will make easy for him a path to Paradise.", source: "Sahih Muslim 2699" },
  { arabic: "الظُّلْمُ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ", translation: "Oppression will be a darkness on the Day of Resurrection.", source: "Sahih al-Bukhari 2447" },
  { arabic: "يَسِّرُوا وَلاَ تُعَسِّرُوا، وَبَشِّرُوا وَلاَ تُنَفِّرُوا", translation: "Make things easy and do not make them difficult, cheer the people up by conveying glad tidings to them and do not repulse them.", source: "Sahih al-Bukhari 69" },
  { arabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ", translation: "The strong is not the one who overcomes the people by his strength, but the strong is the one who controls himself while in anger.", source: "Sahih al-Bukhari 6114" },
  { arabic: "مَا أَنْزَلَ اللَّهُ دَاءً إِلَّا أَنْزَلَ لَهُ شِفَاءً", translation: "Allah has not sent down any disease except that He has also sent down the cure.", source: "Sahih al-Bukhari 5678" },
  { arabic: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", translation: "The best of people are those that bring most benefit to the rest of mankind.", source: "Daraqutni" },
  { arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ", translation: "Fear Allah wherever you are.", source: "Jami at-Tirmidhi 1987" },
  { arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", translation: "A Muslim is the one from whose tongue and hands the Muslims are safe.", source: "Sahih al-Bukhari 10" },
  { arabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ", translation: "Charity does not decrease wealth.", source: "Sahih Muslim 2588" },
  { arabic: "إِنَّ مِنْ أَخْيَرِكُمْ أَحْسَنَكُمْ خُلُقًا", translation: "The best amongst you are those who have the best manners and character.", source: "Sahih al-Bukhari 6029" },
  { arabic: "رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ", translation: "The Lord's pleasure is in the parent's pleasure, and the Lord's anger is in the parent's anger.", source: "Jami at-Tirmidhi 1899" },
  { arabic: "الْبِرُّ حُسْنُ الْخُلُقِ", translation: "Righteousness is good character.", source: "Sahih Muslim 2553" },
  { arabic: "لَا يَدْخُلُ الْجَنَّةَ قَاطِعُ رَحِمٍ", translation: "The one who severs the ties of kinship will not enter Paradise.", source: "Sahih al-Bukhari 5984" },
  { arabic: "أَحَبُّ الْبِلاَدِ إِلَى اللَّهِ مَسَاجِدُهَا", translation: "The most beloved of places to Allah are the mosques.", source: "Sahih Muslim 671" },
  { arabic: "إِيَّاكُمْ وَالظَّنَّ، فَإِنَّ الظَّنَّ أَكْذَبُ الْحَدِيثِ", translation: "Beware of suspicion, for suspicion is the falsest of speech.", source: "Sahih al-Bukhari 5143" },
  { arabic: "مَنْ غَشَّنَا فَلَيْسَ مِنَّا", translation: "Whoever deceives us is not one of us.", source: "Sahih Muslim 101" },
  { arabic: "الْمَرْءُ مَعَ مَنْ أَحَبَّ", translation: "A person will be with those whom he loves.", source: "Sahih al-Bukhari 6168" },
  { arabic: "خَيْرُكُمْ خَيْرُكُمْ لأَهْلِهِ", translation: "The best of you is the one who is best to his family.", source: "Sunan Ibn Majah 1977" },
  { arabic: "مَا أَعْطَى اللَّهُ أَحَدًا شَيْئًا خَيْرًا وَأَوْسَعَ مِنَ الصَّبْرِ", translation: "Allah has not given anyone a blessing better and vaster than patience.", source: "Sahih al-Bukhari 1469" },
  { arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ", translation: "Two words are light on the tongue, heavy on the Scale and beloved to the Most Merciful: Subhan Allahi wa bihamdihi, Subhan Allahil Azim.", source: "Sahih al-Bukhari 6682" }
];
